name: PullRequest 파이프라인
on:
  pull_request:
  workflow_dispatch:
jobs:
  verification:
    runs-on:
      - self-hosted
      - ci
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2 #https://blog.gradle.org/gh-actions
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Unit Test with Gradle
        run: ./gradlew test --stacktrace --info
